apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-rust-wasi
  namespace: default
spec:
  template:
    metadata:
      annotations:
        module.wasm.image/variant: compat-smart
    spec:
      runtimeClassName: crun
      timeoutSeconds: 1
      containers:
      - name: http-server
        image: quay.io/uirlis/helloworld-rust-wasi:v1.0.0
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
          - name: TARGET
            value: "Rust Sample v1"