apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-rust-wasi
  namespace: default
spec:
  template:
    metadata:
      annotations:
        module.wasm.image/variant: compat-smart
    spec:
      runtimeClassName: crun
      timeoutSeconds: 1
      containers:
      - name: http-server
        image:  quay.io/uirlis/helloworld-rust-wasi@sha256:461a8137c024457640dbd67271a19644747db244f09553ede48f8a073017c2eb
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
          - name: TARGET
            value: "Rust Sample v1"